name: fooddelivery
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.4.0
  url_launcher: ^6.1.10
  image_picker: ^1.1.2  
  pdf: ^3.11.1
  printing: ^5.13.3
  responsive_sizer: ^3.3.1
  uuid: ^4.5.1
  mobile_scanner: ^6.0.2
  path_provider: ^2.0.15
  qr_flutter: ^4.1.0
  book_my_seat: ^1.0.1
  flutter_secure_storage: ^9.2.2
  http: ^1.2.2
  # cloud_firestore: ^5.5.0
  flutter_slidable: ^3.1.1
  flutter_riverpod: ^2.6.1
  animated_bottom_navigation_bar: ^1.0.0
  date_picker_timeline: ^1.2.6
  flutter_svg: ^1.1.6
  shared_preferences: ^2.3.3
  auto_size_text_field: ^2.2.4
  expandable_text: ^2.3.0
  hugeicons: ^0.0.7
  awesome_snackbar_content: ^0.1.2
  icons_launcher: ^3.0.0
  sidebarx: ^0.17.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  supabase_flutter: ^2.5.9
  flutter_dotenv: ^5.1.0
  google_maps_flutter: ^2.5.0
  geolocator: ^12.0.0
  duration: ^3.0.13
  location: ^5.0.3
  intl: ^0.19.0
  flutter_polyline_points: ^2.0.0
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  auto_size_text: ^3.0.0


icons_launcher:
  image_path: "images/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter_native_splash:
  # Main splash screen background color (dark purple)
  color: "#4B0082"
  # Image for the splash screen (ensure this is your logo image)
  image: images/logo.png

  # Dark mode specific configurations
  color_dark: "#4B0082"  # Same dark purple for dark mode
  image_dark: images/logo.png  # Dark mode splash image (optional, can be the same)

  # Android 12 and above specific configuration
  android_12:
    # Splash screen background color for Android 12 (dark purple)
    color: "#4B0082"

    # App icon background color (dark red)
    icon_background_color: "#8B0000"
    image: images/logo.png  # Image to use (ensure the logo fits well within a circle)

    # Dark mode configuration for Android 12
    color_dark: "#4B0082"
    icon_background_color_dark: "#8B0000"
    image_dark: images/logo.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.0

flutter:
  assets:
    - images/
  fonts:
    - family: Sail
      fonts:
        - asset: fonts/Sail-Regular.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Medium.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
          
    - family: Sen
      fonts:
        - asset: fonts/Sen-Regular.ttf
        - asset: fonts/Sen-Medium.ttf
        - asset: fonts/Sen-Bold.ttf
        - asset: fonts/Sen-ExtraBold.ttf
          weight: 700
  uses-material-design: true
